### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method withListener

### ISSUE THREAD

**Issue by Erfans3** [ViksaaSkool/AwesomeSplash#24]
I get this error immediately after the circular reveal completes in the emulator.
``
FATAL EXCEPTION: main
                                                                        Process: com.example.erfan.splash, PID: 7531
                                                                        java.lang.NoSuchMethodError: No virtual method withListener(Lcom/nineoldandroids/animation/Animator$AnimatorListener;)Lcom/daimajia/androidanimations/library/YoYo$AnimationComposer; in class Lcom/daimajia/androidanimations/library/YoYo$AnimationComposer; or its super classes (declaration of 'com.daimajia.androidanimations.library.YoYo$AnimationComposer' appears in /data/app/com.example.erfan.splash-1/split_lib_dependencies_apk.apk:classes3.dex)
                                                                            at com.viksaa.sssplash.lib.activity.AwesomeSplash.startLogoAnimation(AwesomeSplash.java:169)
                                                                            at com.viksaa.sssplash.lib.activity.AwesomeSplash$2.onAnimationEnd(AwesomeSplash.java:156)
                                                                            at io.codetail.animation.SupportAnimatorLollipop$1.onAnimationEnd(SupportAnimatorLollipop.java:75)
                                                                            at android.view.RenderNodeAnimator.onFinished(RenderNodeAnimator.java:381)
                                                                            at android.animation.RevealAnimator.onFinished(RevealAnimator.java:43)
                                                                            at android.view.RenderNodeAnimator.callOnFinished(RenderNodeAnimator.java:488)
                                                                            at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                            at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
``
So as the error suggests, the moment the logo is about to be shown, it crashes out and gives me this error. My friend tested it and it worked fine for him, but when he tested it on my laptop with teamviewer, he had no idea what the problem is.
The error is definitely from inside the AwesomeSplash.java and I would appreciate it if you could lend me hand here.

**Comment by yusufonderd** [comment]
same error

**Comment by kiduyu-klaus** [comment]
Same error
