### ISSUE TITLE
AwesomeSplash not working after enabling Proguard

### ISSUE THREAD

**Issue by ridaeh** [ViksaaSkool/AwesomeSplash#25]
When I use Proguard the Splash showed but It bug before showing the next activity.
I get this message :
```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.Error: Can not init easingMethod instance
                                                       at com.b.b.c.a(Unknown Source)
                                                       at com.b.b.b.a(Unknown Source)
                                                       at com.b.b.b.a(Unknown Source)
                                                       at com.b.a.a.i.a.b.a(Unknown Source)
                                                       at com.b.a.a.a.b(Unknown Source)
                                                       at com.b.a.a.c.a(Unknown Source)
                                                       at com.b.a.a.c.a(Unknown Source)
                                                       at com.b.a.a.c$a.a(Unknown Source)
                                                       at com.e.a.a.a.a.n(Unknown Source)
                                                       at com.e.a.a.a.a$1.a(Unknown Source)
                                                       at com.c.a.a.a(Unknown Source)
                                                       at com.c.a.a.onDraw(Unknown Source)
                                                       at android.view.View.draw(View.java:13806)
                                                       at android.view.View.buildDrawingCache(View.java:13067)
                                                       at android.view.View.getDisplayList(View.java:12736)
                                                       at android.view.View.getDisplayList(View.java:12801)
                                                       at android.view.View.draw(View.java:13530)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3228)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3093)
                                                       at android.view.View.getDisplayList(View.java:12755)
                                                       at android.view.View.getDisplayList(View.java:12801)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3210)
                                                       at android.view.View.getDisplayList(View.java:12693)
                                                       at android.view.View.getDisplayList(View.java:12801)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3210)
                                                       at android.view.View.getDisplayList(View.java:12693)
                                                       at android.view.View.getDisplayList(View.java:12801)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3210)
                                                       at android.view.View.getDisplayList(View.java:12693)
                                                       at android.view.View.getDisplayList(View.java:12801)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3210)
                                                       at android.view.View.getDisplayList(View.java:12693)
                                                       at android.view.View.getDisplayList(View.java:12801)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3210)
                                                       at android.view.View.getDisplayList(View.java:12693)
                                                       at android.view.View.getDisplayList(View.java:12801)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3210)
                                                       at android.view.View.getDisplayList(View.java:12693)
                                                       at android.view.View.getDisplayList(View.java:12801)
                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3210)
                                                       at android.view.View.getDisplayList(View.java:12693)
                                                       at android.view.View.getDisplayList(View.java:12801)
                                                       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1144)
                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2278)
                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2150)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1961)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4538)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:525)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                                                       at android.os.Handler.handleCallback(Handler.java:615)
                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                       at android.os.Looper.loop(Looper.java:137)
                                                       at android.app.ActivityThread.main(ActivityThread.java:4921)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
                                                       at dalvik.system.NativeStart.main(Native Method)
```
Could you help me ?
thanks in advance

**Comment by ViksaaSkool** [comment]
I'll take a look, but I'd go for not obfuscating the lib since it's open source, there's no point...

**Comment by Aym9n** [comment]
same issue here, just disable proguard and should go fine

**Comment by Aym9n** [comment]
Just add this code to **proguard-rules.pro** file in app module

> 
> -keep class cn.pedant.SweetAlert.** { *; }
>  -dontwarn cn.pedant.SweetAlert.**
>  -keepnames class cn.pedant.SweetAlert.**

**Comment by ammara121** [comment]
Hi I have problem about Awesome splash please help Am student working on fyp.
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    implementation('com.github.ViksaaSkool:AwesomeSplash:v1.0.0') {
        exclude group: 'com.android.support'
    }
    androidTestImplementation ('com.android.support.test.espresso:espresso-core:3.0.2', {
        exclude group: 'com.android.support', module: 'support annotations'
    })
}

//code
 @Override
    public void initSplash(ConfigSplash configSplash) {
        Toast.makeText(this,"hlw",Toast.LENGTH_SHORT).show();
         ActionBar actionBar=getSupportActionBar();
        actionBar.hide();
        getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,WindowManager.LayoutParams.FLAG_FULLSCREEN);   //give full screen

        //Set backgroud colour
        Toast.makeText(this,"hlw",Toast.LENGTH_SHORT).show();
        configSplash.setBackgroundColor(R.color.colorPrimary);
        configSplash.setAnimCircularRevealDuration(3000);
        configSplash.setRevealFlagX(Flags.REVEAL_BOTTOM);
        configSplash.setRevealFlagX(Flags.REVEAL_LEFT);
        configSplash.setLogoSplash(R.drawable.zz);
        configSplash.setAnimLogoSplashDuration(5000);
        configSplash.setAnimLogoSplashTechnique(Techniques.Bounce);
        configSplash.setTitleSplash("Bus Application");
        configSplash.setTitleTextColor(R.color.colorAccent);
        configSplash.setAnimTitleDuration(3000);
        configSplash.setAnimTitleTechnique(Techniques.FlipInX);
    }

    @Override
    public void animationsFinished() {
        Intent intent=new Intent(this,Main2Activity.class);
        startActivity(intent);

    }
}


Application crash without show any msg....
